version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
      - php-fpm
  php-fpm:
    build: .
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: cakephp
      MYSQL_USER: cakephp
      MYSQL_PASSWORD: cakephp
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: cakephp
      PMA_PASSWORD: cakephp
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data: {}
